---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos/7

suites:
  - name: default
    run_list:
      - recipe[aws-ssm-test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      aws-ssm-test:
        aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
        aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
